# Generated by Django 5.0.7 on 2024-07-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0005_rename_blog_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='author',
            new_name='authors',
        ),
    ]
