# Generated by Django 5.0.7 on 2024-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0006_rename_author_blogs_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
