# Generated by Django 5.0.7 on 2024-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0007_blog_delete_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
